import Foundation
import UIKit

class ShareService {
    
    static func formatAnalysisForSharing(analysisResult: String, teamConfigs: [TeamAnalysisConfig]) -> String {
        var shareText = "NBA Team Comparison Analysis\n\n"
        
        // Add teams being analyzed
        shareText += "Teams Analyzed:\n"
        for config in teamConfigs {
            shareText += "• \(config.team.fullName) (\(TeamAnalysisConfig.seasonDisplay(config.season))) - \(config.gameRangeDisplay)\n"
        }
        shareText += "\n"
        
        // Clean up the analysis result for sharing
        let cleanedAnalysis = cleanAnalysisForSharing(analysisResult)
        shareText += cleanedAnalysis
        
        // Add attribution
        shareText += "\n\nGenerated by NBA Team Analyzer"
        
        return shareText
    }
    
    private static func cleanAnalysisForSharing(_ analysis: String) -> String {
        var cleaned = analysis
        
        // Remove markdown symbols but keep structure
        cleaned = cleaned.replacingOccurrences(of: "# ", with: "")
        cleaned = cleaned.replacingOccurrences(of: "## ", with: "")
        cleaned = cleaned.replacingOccurrences(of: "### ", with: "")
        cleaned = cleaned.replacingOccurrences(of: "**", with: "")
        cleaned = cleaned.replacingOccurrences(of: "• ", with: "• ")
        
        // Ensure proper spacing
        cleaned = cleaned.replacingOccurrences(of: "\n\n\n", with: "\n\n")
        
        return cleaned
    }
    
    static func shareAnalysis(analysisResult: String, teamConfigs: [TeamAnalysisConfig]) {
        let shareText = formatAnalysisForSharing(analysisResult: analysisResult, teamConfigs: teamConfigs)
        
        // Create activity view controller for sharing
        let activityVC = UIActivityViewController(activityItems: [shareText], applicationActivities: nil)
        
        // Present the share sheet
        if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let window = windowScene.windows.first {
            window.rootViewController?.present(activityVC, animated: true)
        }
    }
} 